### ISSUE TITLE
Remove Python 2 dependency

### ISSUE THREAD

**Issue by Peque** [bqlabs/apio#20]
It seems the only thing preventing full Python 3 compatibility is SCons. Maybe it could be replaced by another Python build system (perhaps [WAF](https://github.com/waf-project/waf)?).

**Comment by Jesus89** [comment]
Hi!, the final goal is to converge with http://platformio.org/ (it uses Python2 and SCons). However we will study WAF to reach Python3 compatibility. Thanks!
