### ISSUE TITLE
Implement the apio debug lsusb command

### ISSUE THREAD

**Issue by Obijuan** [bqlabs/apio#27]
This apio command will list the USB devices
It invokes the listdevs binary, located in the packages tools-usb-ftdi  (that is intalled by means of the apio debug install command)

**Comment by Obijuan** [comment]
Let's change the command for system:

apio system lsusb

**Comment by Jesus89** [comment]
Done: 2764cbb6278db9b0a5a81850b8e35e5f2132430e
